### ISSUE TITLE
Consider using hashabler instead of hashable?

### ISSUE THREAD

**Issue by jberryman** [tibbe/unordered-containers#117]
Would you be interested in merging changes that moved from `hashable` to my [`hashabler`](https://hackage.haskell.org/package/hashabler) project? [Here](http://brandon.si/code/announcing-hashabler-like-hashable/)'s a blog post I wrote that introduces an older version.

This would leave the API more or less unchanged but would
  - allow the data structures here to be safely public facing, by using SipHash
  - permit extending the API to make the choice of hash function user-configurable
  - be generally less sketchy
  - support consistent cross platform hashing, and in turn makes possible consistent serialization of these structures

The downsides might include:
  - `hashable` may have greater backwards compatibility
  - `hashable` is more widely used and users would need to redefine any custom data type instances for `hashabler`'s `Hashable`
  - we don't yet support deriving instances with TH

The last two downsides will get mostly solved together when I define a TH deriving routine that's a drop-in replacement for `hashable`'s, at some point.

I'm not sure when I'd be able to get to a PR, but I wanted to float the idea first. Let me know if you're interested and would like more details about what that might look like. Also if this idea sounds appealing but you have changes you'd want to see made in `hashabler` first, or have any other thoughts. Thanks!

**Comment by tibbe** [comment]
Hi Brandon!

From reading the blog post and skimming the library API I can't tell if you already knew, but @bos and I tried to switch hashable to better hash functions (SipHash and Thomas Wang's integer hash) in the past. The problem is that we couldn't get a working implementation that was both 1) correct and 2) fast. Trying to make it fast (by using SSE) and support initialization of a proper random seed led to lots of bugs (i.e. segfaults due to interaction with the GHC linker, alignment issues, etc).

Making it fast it really key, because if unordered-containers is not faster than containers there's no point in having it. After all, the data structures in containers are not susceptible to the hashing attacks SipHash was designed to prevent and they offer strictly more functionality (because of their sorted nature).

So a very first step, before we talk about backwards compatibility and APIs, would be to see if unordered-containers is still faster than containers when using hashabler.

**Comment by jberryman** [comment]
Thanks for the feedback! I think I got promising promising performance results with my SipHash but I'll need to revisit it and maybe do some more detailed benchmarking, and will report back.

> because if unordered-containers is not faster than containers there's no point in having it.

good point.

**Comment by jberryman** [comment]
IYI: I've copied some of `hashable`'s benchmarks into my (really messy) benchmark suite. Quick summary of current performance (TLDR it's all slower to varying degrees):

for my FNV1a hash:
- hashabler is a constant ~10ns slower for bytestings, than `hashable` (which is significant for small bytestrings)
- `Text` similary is ~4ns slower  for smaller sizes, with the difference becoming insignificant for linger strings
- hashing lists takes ~20% more time (I still haven't figured out the best story there, to get fusion and all that working reliably)

And for my siphash variant:
- starts at 63ns for a 5-byte `ByteString` (vs 12ns for `hashable`)
- compares better as bytestrings or text get longer until identical performance to `hashable` at 512 bytes

(Pretty happy with the siphash performance, considering)

Feel free to close if you like. I'll comment again if the performance improves or I find out anything else interesting.

**Comment by tibbe** [comment]
Thanks for following up. If your hashable implementation comes close to the current performance on the unordered-containers benchmark suite please do let me know. I'd trade a little bit of performance for SipHash.
