### ISSUE TITLE
Generic Instance

### ISSUE THREAD

**Issue by 2piix** [tibbe/unordered-containers#53]
Howdy,

Can we have Generic instances for HashMaps and HashSets?  I wrote a patch, if you are interested.

-Alex

**Comment by jaspervdj** [comment]
To come back on this, I don't think this and #54 are super useful for now.

Most practical applications of `Generic` require that the whole datatype tree, i.e., including the datatypes underneath, derive `Generic`. Since we can't have this for unlifted types (`Array#`), this doesn't really work well. I the rare cases where we do need the instance, using `StandaloneDeriving` as I demonstrated in #25 should do the trick.

**Comment by treeowl** [comment]
This is becoming a problem for me personally. How hard would it be to make a bogus instance like the ones in `containers` while waiting for a better answer?

**Comment by neongreen** [comment]
Today I wanted to use generic-lens on a HashMap, but failed :(

**Comment by treeowl** [comment]
Sorry, that's really not going to happen. `Generic` instances are for concrete/open types, but `HashMap`'s representation is kept abstract.
